trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y mono-complete
    mono --version
  displayName: 'Install Mono'

- script: |
    dotnet --version
    dotnet helloworld.cs
    mcs helloworld.cs
  displayName: 'Install .NET SDK'

